name: light-house-CI
on: [ push ]
jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 17
      - run: yarn && yarn global add @lhci/cli
      - run: yarn build:dev && yarn export

      - name: run lighthouse CI
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
        run: |
          lhci autorun || echo "fail"
