name: Run lighthouse CI When Push
on: [ push ]
jobs:
  lhci:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v2

      - name: Use Node.js 17.3.1
        uses: actions/setup-node@v1
        with:
          node-version: 17.3.1

      - name: Install packages
        run: |
          yarn

      - name: Build
        run: |
          yarn build && yarn export

      - name: Run Lighthouse CI
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
        run: |
          yarn add global @lhci/cli
          lhci autorun || echo "Fail to Run Lighthouse CI!"